### ISSUE TITLE
Plz update get magnet links in [quote] or [code] forum

### ISSUE THREAD

**Issue by m4xJ** [MichelePezza/CopyLinksplusplus#4]
I can't get magnet links on this forum (Warning aldult forum!!)
Ex link: https://www.sehuatang.org/thread-374311-1-1.html
It'ss seem magnet link on [code] forum
Plz add more function, thankyou so much!

**Comment by MichelePezza** [comment]
I'm going to release a new version with a better regex for magnet link.
In order to detect text link you must install additional addon I will publish instruction on mozilla addon site.

Thx
MP

**Comment by mrhuzg** [comment]
Thankyou, i waiting your publish!

**Comment by m4xJ** [comment]
> 
> 
> I'm going to release a new version with a better regex for magnet link.
> In order to detect text link you must install additional addon I will publish instruction on mozilla addon site.
> 
> Thx
> MP

Thankyou so much!

**Comment by m4xJ** [comment]
Hi!
I still can't copy magnet link on this forum https://www.sehuatang.org/thread-374311-1-1.html
I installed add-on on Firefox, but it's doesn't working
Plz fix! Thankyou so much

**Comment by MichelePezza** [comment]
Copylinks++ copy the links.... It means the clickable link
but in the forum you wrote the "magnet url" **is not a link** but a **text!**
So what..
we have to use another extension together with Copylinks++
to transform "text url" in "clickable link".
I suggest 2 addons Linkificator or Linkify++, both from other authors,
and you have to choose the one you like ad install it
but in order to transform magnet url text you need to set the extension as i told in 
["About this extension"](https://addons.mozilla.org/en-US/firefox/addon/copylinksplusplus/)


Ciao 
MP

**Comment by m4xJ** [comment]
Thankyou so much for your supports, i did and working fine with Linkify Plus Plus
